<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <RootNamespace>Microsoft.CST.RecursiveExtractor.Benchmarks</RootNamespace>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <LangVersion>10.0</LangVersion>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RecursiveExtractor\RecursiveExtractor.csproj" />
  </ItemGroup>

</Project>
