# Azure Pipelines
# https://aka.ms/yaml

name: RecursiveExtractor_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - RecursiveExtractor
    - RecursiveExtractor.Cli
pr:
  branches:
    include:
    - main
  paths:
    include:
    - Pipelines
    - RecursiveExtractor
    - RecursiveExtractor.Blazor
    - RecursiveExtractor.Cli
    - RecursiveExtractor.Tests
    - RecursiveExtractor.sln

stages:
- stage: Test
  jobs:
  - template: templates/dotnet-test-job.yml
    parameters:
      dotnetVersion: '3.1.x'
      projectPath: 'RecursiveExtractor.Tests/RecursiveExtractor.Tests.csproj'

- stage: SDL
  dependsOn: Test
  jobs:
  - template: templates/sdl-job.yml
    parameters:
      serviceTreeID: '1f6713ed-e0f1-4691-93a2-7e01bcf04acb'
      
- stage: Build
  dependsOn: Test
  jobs:
  - template: templates/nuget-build-job.yml
    parameters:
      jobName: 'pack_lib'     
      dotnetVersion: '3.1.x'
      projectPath: 'RecursiveExtractor/RecursiveExtractor.csproj'
      projectName: 'RecursiveExtractor'
  - template: templates/nuget-build-job-framework.yml
    parameters:
      jobName: 'pack_cli'
      dotnetVersion: '3.1.x'
      publishFramework: 'netcoreapp3.1'
      projectPath: 'RecursiveExtractor.Cli/RecursiveExtractor.Cli.csproj'
      projectName: 'RecursiveExtractor_CLI'

- stage: Release
  dependsOn:
  - SDL
  - Build
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
  jobs:
  - job: sign_hash_release
    displayName: Code Sign, Generate Hashes, Publish Public Releases
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: Download Unsigned Archives
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        itemPattern: 'Unsigned_Binaries/*.zip'
        downloadPath: '$(Build.BinariesDirectory)'
    - task: ExtractFiles@1
      displayName: Extract Artifacts for Signing
      inputs:
        archiveFilePatterns: '$(Build.BinariesDirectory)\*.zip'
        destinationFolder: '$(Build.BinariesDirectory)'
        cleanDestinationFolder: false
    - task: AntiMalware@3
      displayName: Anti-Malware Scan
      inputs:
        InputType: 'Basic'
        ScanType: 'CustomScan'
        FileDirPath: '$(Build.BinariesDirectory)'
        EnableServices: true
        SupportLogOnError: true
        TreatSignatureUpdateFailureAs: 'Warning'
        SignatureFreshness: 'UpToDate'
        TreatStaleSignatureAs: 'Warning'
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '2.1.804'
    - task: EsrpCodeSigning@1
      displayName: Code Sign Nuget Packages
      inputs:
        ConnectedServiceName: 'RecursiveExtractor_CodeSign'
        FolderPath: '$(Build.BinariesDirectory)'
        Pattern: '*.nupkg, *.snupkg'
        signConfigType: 'inlineSignParams'
        inlineOperation: |
          [
                  {
                      "KeyCode" : "CP-401405",
                      "OperationCode" : "NuGetSign",
                      "Parameters" : {},
                      "ToolName" : "sign",
                      "ToolVersion" : "1.0"
                  },
                  {
                      "KeyCode" : "CP-401405",
                      "OperationCode" : "NuGetVerify",
                      "Parameters" : {},
                      "ToolName" : "sign",
                      "ToolVersion" : "1.0"
                  }
              ]
        SessionTimeout: '60'
        MaxConcurrency: '50'
        MaxRetryAttempts: '5'
    - powershell: 'Get-ChildItem -Path ''$(Build.BinariesDirectory)'' -Recurse CodeSign* | foreach { Remove-Item -Path $_.FullName }'
      displayName: 'Delete Code Sign Summaries'
    - task: PowerShell@2
      displayName: Move NuGet Packages
      inputs:
        targetType: 'inline'
        script: |
          mv $env:BUILD_BINARIESDIRECTORY/*.nupkg $env:BUILD_STAGINGDIRECTORY/
          mv $env:BUILD_BINARIESDIRECTORY/*.snupkg $env:BUILD_STAGINGDIRECTORY/
    - task: PublishPipelineArtifact@1
      displayName: Pipeline Publish Signed Artifacts
      inputs:
        targetPath: '$(Build.StagingDirectory)'
        artifact: 'Signed_Binaries'
    - task: NuGetCommand@2
      displayName: Publish NuGet Packages
      inputs:
        command: 'push'
        packagesToPush: '$(Build.StagingDirectory)/*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'CST-E Nuget CI'
        verbosityPush: 'Normal'