name: RecursiveExtractor_PR_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: templates
      type: git
      name: General/OSS-Tools-Pipeline-Templates
      ref: refs/tags/v2.0.4
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
      
variables:
  BuildConfiguration: 'Release'
  DotnetVersion: '10.0.x'

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: MSSecurity-1ES-Build-Agents-Pool
      image: MSSecurity-1ES-Windows-2022
      os: windows
    sdl:
      armory:
        enabled: false
    stages:
    - stage: Test
      dependsOn: []
      jobs:
      - template: dotnet-test-job.yml@templates
        parameters:
          jobName: 'lib_dotnet_test_windows'
          dotnetVersions: ['8.0.x', '9.0.x', '10.0.x']
          projectPath: 'RecursiveExtractor.Tests/RecursiveExtractor.Tests.csproj'
          poolName: MSSecurity-1ES-Build-Agents-Pool
          poolImage: MSSecurity-1ES-Windows-2022
          poolOs: windows
          dotnetTestArgs: '--logger trx --results-directory TestResults -- --coverage'
          includeNuGetOrg: false
          nugetFeedsToUse: 'config'
          nugetConfigPath: 'nuget.config'
          onInit:
            - task: NuGetAuthenticate@1
  
      - template: dotnet-test-job.yml@templates
        parameters:
          jobName: 'cli_dotnet_test_windows'
          dotnetVersions: ['8.0.x', '9.0.x', '10.0.x']
          projectPath: 'RecursiveExtractor.Cli.Tests/RecursiveExtractor.Cli.Tests.csproj'
          poolName: MSSecurity-1ES-Build-Agents-Pool
          poolImage: MSSecurity-1ES-Windows-2022
          poolOs: windows
          dotnetTestArgs: '--logger trx --results-directory TestResults -- --coverage'
          includeNuGetOrg: false
          nugetFeedsToUse: 'config'
          nugetConfigPath: 'nuget.config'
          onInit:
            - task: NuGetAuthenticate@1

    - stage: Build
      dependsOn:
      - Test
      jobs:
      - template: nuget-build-job.yml@templates
        parameters:
          jobName: 'pack_lib'
          buildConfiguration: ${{ variables.BuildConfiguration }}
          dotnetVersion: ${{ variables.DotnetVersion }}
          projectPath: 'RecursiveExtractor/RecursiveExtractor.csproj'
          projectName: 'RecursiveExtractor'
          customPackFlags: '/p:ContinuousIntegrationBuild=true'
          artifactName: 'lib-archive'
          includeNuGetOrg: false
          nugetFeedsToUse: 'config'
          nugetConfigPath: 'nuget.config'
          onInit:
            - task: NuGetAuthenticate@1
          preBuild:
          - template: nbgv-set-version-steps.yml@templates
  
      - template: nuget-build-job.yml@templates
        parameters:
          jobName: 'pack_cli'
          buildConfiguration: ${{ variables.BuildConfiguration }}
          dotnetVersion: ${{ variables.DotnetVersion }}
          projectPath: 'RecursiveExtractor.Cli/RecursiveExtractor.Cli.csproj'
          projectName: 'RecursiveExtractor_CLI'
          customPackFlags: '/p:ContinuousIntegrationBuild=true'
          artifactName: 'cli-archive'
          includeNuGetOrg: false
          nugetFeedsToUse: 'config'
          nugetConfigPath: 'nuget.config'
          onInit:
            - task: NuGetAuthenticate@1
          preBuild:
          - template: nbgv-set-version-steps.yml@templates
