# Azure Pipelines
# https://aka.ms/yaml

name: RecursiveExtractor_PR_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: templates
      type: git
      name: SecurityEngineering/OSS-Tools-Pipeline-Templates
      #ref: refs/tags/v1.0.6
      ref: da/fix-policheck-nuget

variables:
  BuildConfiguration: 'Release'
  DotnetVersion: '7.0.x'
  DotnetVersionLTS: '6.0.x'

stages:
- stage: Test
  dependsOn: []
  jobs:
  - template: dotnet-test-job.yml@templates
    parameters:
      jobName: 'dotnet_test_windows'
      dotnetVersion: ${{ variables.DotnetVersion }}
      dotnetVersionLTS: ${{ variables.DotnetVersionLTS }}
      vmImage: 'oss-tools-win2022_1es-managed'
      projectPath: 'RecursiveExtractor.Tests/RecursiveExtractor.Tests.csproj'

- stage: SDL
  dependsOn: []
  jobs:
  - template: sdl-job.yml@templates
    parameters:
      preScan:
      - template: policheck-exclusion-steps.yml@templates
        parameters:
          ExcludeFolderPathStart: 'RecursiveExtractor.Tests'
      policheckExclusionFile: $(Build.SourcesDirectory)/PolicheckExclusions.xml

- stage: Build
  dependsOn:
  - Test
  jobs:
  - template: nuget-build-job.yml@templates
    parameters:
      jobName: 'pack_lib'
      buildConfiguration: ${{ variables.BuildConfiguration }}
      dotnetVersion: ${{ variables.DotnetVersion }}
      projectPath: 'RecursiveExtractor/RecursiveExtractor.csproj'
      projectName: 'RecursiveExtractor'
      preBuild:
      - template: nbgv-set-version-steps.yml@templates
  - template: nuget-build-job.yml@templates
    parameters:
      jobName: 'pack_cli'
      buildConfiguration: ${{ variables.BuildConfiguration }}
      dotnetVersion: ${{ variables.DotnetVersion }}
      projectPath: 'RecursiveExtractor.Cli/RecursiveExtractor.Cli.csproj'
      projectName: 'RecursiveExtractor_CLI'
      preBuild:
      - template: nbgv-set-version-steps.yml@templates
      - task: UseDotNet@2
        displayName: Install Dotnet SDK
        inputs:
          packageType: 'sdk'
          version: 6.x
