name: Publish Blazor

on:
  push:
    branches: [ main ]
  pr:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Get nbgv
      run: dotnet tool install -g nbgv
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish RecursiveExtractor.Blazor --configuration Release --no-restore 
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.4
      with:
        publish_branch: gh-pages
        # Set an input directory for deployment.
        publish_dir: RecursiveExtractor.Blazor/bin/Release/netstandard2.1/publish/wwwroot
